africandesigns/urls.py
from django.conf.urls import patterns, url

from africandesigns import views

urlpatterns = patterns('',
    url(r'^register/$', views.register, name = 'register'),
    url(r'^signin/$', views.signin, name = 'signin'),
    url(r'^home/$', views.home, name = 'home'),
    url(r'^logout/$', views.logout, name = 'logout'),
    url(r'^add_store/$', views.add_store, name = 'add_store'),
    url(r'^store/(?P<store_id>\d+)/$', views.store, name = 'store'),
    url(r'^add_product/$', views.add_product, name = 'add_product'),
    url(r'^product/(?P<product_id>\d+)/$', views.product, name = 'product'),
    url(r'^add_item_to_cart/(?P<product_id>\d+)/$', views.add_item_to_cart, name = 'add_item_to_cart'),
    url(r'^shopping_cart/$', views.shopping_cart, name = 'shopping_cart'),
    url(r'^total_shopping_items/$', views.total_shopping_items, name = 'total_shopping_items'),
    url(r'^edit_product/(?P<product_id>\d+)/$', views.edit_product, name = 'edit_product'),
    url(r'^edit_store/(?P<store_id>\d+)/$', views.edit_store, name = 'edit_store'),


    url(r'^page/$', views.page, name = 'page'),
    url(r'^load/$', views.load, name = 'load'),
    url(r'^shopping_cart/(?P<store_id>\d+)/(?P<product_index>\d+)/$', views.shopping_cart, name = 'shopping_cart'),
    url(r'^delete_product/(?P<product_id>\d+)/$', views.delete_product, name='delete_product'),
    url(r'^checkout/(?P<store_id>\d+)/$', views.checkout, name = 'checkout'),

    url(r'^orders/(?P<store_id>\w+)/$', views.orders, name = 'orders'),
    url(r'^orders/(?P<store_id>\w+)/(?P<order_filter>\w+)/$', views.orders, name = 'orders'),

    url(r'^order/(?P<order_id>\d+)/$', views.order, name = 'order'),
    url(r'^update_shipping/(?P<order_id>\d+)/$', views.update_shipping, name = 'update_shipping'),
    url(r'^shipping/$', views.shipping, name = 'shipping'),

    url(r'^my_orders/$', views.my_orders, name = 'my_orders'),
    url(r'^my_orders/(?P<order_filter>\w+)/$', views.my_orders, name = 'my_orders'),
    url(r'^my_order/(?P<order_id>\d+)/$', views.my_order, name = 'my_order'),

    url(r'^my_stores/$', views.my_stores, name = 'my_stores'),

    url(r'^edit_account/$', views.edit_account, name = 'edit_account'),
    url(r'^change_password/$', views.change_password, name = 'change_password'),
    url(r'^store_admin/(?P<store_id>\d+)/$', views.store_admin, name = 'store_admin'),
    url(r'^remove_admin/(?P<admin_id>\d+)/$', views.remove_admin, name = 'remove_admin'),

    url(r'^e_content/$', views.e_content, name = 'e_content'),












)

africandesigns_web_app/urls.py
from django.conf.urls import patterns, include, url

from africandesigns import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'africandesigns_web_app.views.home', name='home'),
    # url(r'^africandesigns_web_app/', include('africandesigns_web_app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^africandesigns/', include('africandesigns.urls', namespace="africandesigns")),
    url(r'^$', views.home, name = 'home'),
)

africandesigns/models.py
from django.db import models
from django.contrib.auth import get_user_model #django user model

# Create your models here.

class Stores(models.Model):
    """Model to hold store product information"""
    owner_id = models.IntegerField()
    name = models.TextField()
    description = models.TextField()
    status = models.IntegerField(default=0) #0 = inactive, 1=active, #2=suspended
    zipcode = models.IntegerField(default=0) #store zipcode
    date_created = models.DateTimeField()

    def owner(self):
	user = get_user_model().objects.get(id = self.owner_id)
	return user

class Admins(models.Model):
    """Other admins of store apart from owner"""
    store = models.ForeignKey(Stores)
    admin_id = models.IntegerField()

    def admin(self):
	user = get_user_model().objects.get(id = self.admin_id)
	return user

class Products(models.Model):
    """Model to hold store product information"""
    store_id = models.IntegerField()
    name = models.TextField()
    quantity = models.IntegerField()
    price = models.FloatField()
    description = models.TextField()
    date_added = models.DateTimeField()

    def store(self):
	store = Stores.objects.get(id = self.store_id)
	return store


class Shipping(models.Model):
    """Shipping cost"""
    product = models.ForeignKey(Products)
    cost = models.FloatField(default=0)
    duration = models.TextField(default=0)
    weight_pounds = models.IntegerField(default=0)
    weight_ounces = models.FloatField(default=0)
    zipcode = models.IntegerField(default=0) #zipcode product is being shipped from
    date_added = models.DateTimeField()

class Orders_Shipping(models.Model):
    """buyer's shipping information"""
    store_id = models.IntegerField(default=0)
    buyer_id = models.IntegerField()
    address = models.TextField(default='null')
    city = models.TextField(default='null')
    state = models.TextField(default='null')
    zipcode = models.IntegerField()
    country = models.TextField(default='United States')
    shipped = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    date_ordered = models.DateTimeField()

    def buyer(self):
	user = get_user_model().objects.get(id = self.buyer_id)
	return user

    def seller(self):
	store = Stores.objects.get(id = self.store_id)
	return store

class Orders_Products(models.Model):
    """Produts in Orders"""
    order = models.ForeignKey(Orders_Shipping)
    product_id = models.IntegerField()

    def get_product(self):
	product = Products.objects.get(id = self.product_id)
	return product


class Images(models.Model):
    print "hhh"
    """Model to hold images of products"""
    product = models.ForeignKey(Products)
    image = models.ImageField(upload_to = 'africandesigns/static/products')

    def image_name(self):
	""" image sub path (products/[image name]) needed to display images"""
	return (str(self.image.url.split('/')[2]) + '/' + str(self.image.url.split('/')[3]))

class User_Shipping(models.Model):
    """user's shipping information"""
    user_id = models.IntegerField(default=0)
    address = models.TextField(default='null')
    city = models.TextField(default='null')
    state = models.TextField(default='null')
    zipcode = models.IntegerField()
    country = models.TextField(default='United States')

    def get_user(self):
	user = get_user_model().objects.get(id = self.user_id)
	return user





    

africandesigns/views.py
# Create your views here.

from django.http import HttpResponse

from django.shortcuts import render
from django.contrib.auth.models import User

from django.contrib.auth import get_user_model #django user model

from africandesigns.forms import * #file where forms are located

from africandesigns.models import * #database

from django.contrib import messages #flash messages
from django.shortcuts import redirect

from django.http import HttpResponseRedirect

from django.contrib.auth import authenticate, login, logout

from datetime import datetime # date library

from django.shortcuts import get_object_or_404 #404 error if the data requested is not in the database

from django.core.urlresolvers import reverse

from django.core.exceptions import ObjectDoesNotExist # exception



"""  """
def page(request):
    return render(request, 'africandesigns/page.html')

def e_content(request):
    return render(request, 'africandesigns/e_content.html')


"""  """
def load(request):
    return render(request, 'africandesigns/load.html')


""" home """
def home(request):
    products = Products.objects.all()
    return render(request, 'africandesigns/home.html', {'products': products,})

""" user registration """
def register(request):
    if request.method == 'POST': #if the form has been submitted
	form = RegisterForm(request.POST)
	if form.is_valid(): #form is validated
	    # add user to database

	    user = get_user_model().objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password'])

	    user.first_name = form.cleaned_data['first_name']
	    user.last_name = form.cleaned_data['last_name']
	    user.is_active = True
	    user.save()

	    messages.add_message(request, messages.INFO, "Registration successful!")
	    #render(request, 'africandesigns/signin.html')
	    return HttpResponseRedirect(reverse('africandesigns:signin'))

    else:
        form = RegisterForm()
    return render(request, 'africandesigns/register.html',  {'form': form, 'title': 'Register'})

""" user signin """
def signin(request):
    if request.method == 'POST':
	form = SigninForm(request.POST)
	if form.is_valid():
	    # check email and password match
	    query_user = get_user_model().objects.filter(email = form.cleaned_data['email'])
	    print "len", len(query_user)
	    #query_user[0].delete()
	    #query_user[0].save()
	    if len(query_user) == 1: 
		user = query_user[0]
		if user.check_password(form.cleaned_data['password']) == True: # authentication successful
		    if user.is_active: # account is active
		        messages.add_message(request, messages.INFO, "You have successfully signed in!")
		        #store user in session to indicate user is logged in
		        request.session['user'] = user
			#login
			#login(request, user)
    		        return HttpResponseRedirect(reverse('africandesigns:home'))
		    else: # account is inactive
	    	        messages.add_message(request, messages.INFO, "Sorry, you cannot login because you account has been deactivated!")
    			return render(request, 'africandesigns/signin.html', {'form': form, 'title': 'Signin'}) 	
	        else: # account is inactive
	            messages.add_message(request, messages.INFO, "Sorry, email address and/or password is incorrect!")
    		    return render(request, 'africandesigns/signin.html', {'form': form, 'title': 'Signin'})

    else:
	form = SigninForm()
    return render(request, 'africandesigns/signin.html', {'form': form, 'title': 'Signin'})

""" Logout user """ 
def logout(request):
    #remove user from session to logout user if user is currently logged in
    if 'user' in request.session:
	del request.session['user']
	messages.add_message(request, messages.INFO, "You have successfully logged out!")
    return HttpResponseRedirect(reverse('africandesigns:signin'))


""" add store """
def add_store(request):
    if request.method == 'POST': #if the form has been submitted
	form = AddStoreForm(request.POST)
	if form.is_valid(): #form is validated
	    # add store to database
	    store = Stores(owner_id = request.session['user'].id, name = form.cleaned_data['name'], description = form.cleaned_data['description'], status = form.cleaned_data['status'], zipcode = form.cleaned_data['zipcode'], date_created = datetime.now())

	    store.save()

	    messages.add_message(request, messages.INFO, "Store successfully added!")
	    return HttpResponseRedirect(reverse('africandesigns:store',  kwargs={'store_id': store.id})) 
 
    else:
        form = AddStoreForm()
    return render(request, 'africandesigns/add_store.html',  {'form': form, 'title': 'Add Store'})

""" store """
def store(request, store_id):
    #return HttpResponse("Hello, world. You're at the store.")
    store = Stores.objects.get(id = store_id)
    #add store to session
    request.session['store'] = store
    #store = Stores.objects.all()
    print store.name
    products = Products.objects.filter(store_id = store_id)


    #check if user is logged in
    if 'user' in request.session:

        try:
	    admin = Admins.objects.get(admin_id = request.session['user'].id)
	    is_admin = True
        except ObjectDoesNotExist:
	    is_admin = False

    else:
	is_admin = False

    return render(request, 'africandesigns/store.html',  {'title': 'Store', 'store': store, 'products': products, 'is_admin': is_admin,})

    """ s = Products.objects.all()
    for a in s:
	a.delete()
	print "v" """


import os


""" add product """
def add_product(request):
    if request.method == 'POST': #if the form has been submitted
	form = AddProductForm(request.POST)
	if form.is_valid(): #form is validated
	    # add product to database
	    product= Products(store_id = request.session['store'].id, name = form.cleaned_data['name'], description = form.cleaned_data['description'], quantity = form.cleaned_data['quantity'], price = form.cleaned_data['price'], date_added = datetime.now())

	    product.save()

	    if form.cleaned_data['ounces'] == '':
		ounces = 0
	    else:
		ounces = form.cleaned_data['ounces']

	    shipping = product.shipping_set.create(weight_pounds = form.cleaned_data['pounds'], weight_ounces = ounces, zipcode = form.cleaned_data['zipcode'], date_added = datetime.now())

	    shipping.save()

	    if('image1' in request.FILES):
	        image = product.images_set.create(image = request.FILES['image1'])
	    	image.save()
		#save image filename as productid_[product id number]_imageid[image id number]
		#image.image.name = 'productid_' + str(product.id) + '_imageid_' + str(image.id)
    	        #image.save()
		
		print "1"
	    if('image2' in request.FILES):
	        image = product.images_set.create(image = request.FILES['image2'])
	    	image.save()
		#image.image.name = 'productid_' + str(product.id) + '_imageid_' + str(image.id)
    	        #image.save()
		print "2"
	    if('image3' in request.FILES):
	        image = product.images_set.create(image = request.FILES['image3'])
	    	image.save()
		#image.image.name = 'productid_' + str(product.id) + '_imageid_' + str(image.id)
    	        #image.save()
		print "3"

	    product.save()

	    print "yes"
	    messages.add_message(request, messages.INFO, "Product successfully added!")
	    return HttpResponseRedirect(reverse('africandesigns:product', kwargs={'product_id': product.id})) 

            #print "bbb", os.path.splitext(request.FILES['image1'].name)[0], os.path.splitext(request.FILES['image1'].name)  # Will return just 'file'
            #return HttpResponseRedirect(reverse('africandesigns:product', kwargs={'product_id': 1})) 

        else:
	    print "invalid entry!"
    else:
	data = {
	    'zipcode': request.session['store'].zipcode,
	}
        form = AddProductForm()
        return render(request, 'africandesigns/add_product.html',  {'form': form, 'title': 'Add Product'})





""" product """
def product(request, product_id):
    product = Products.objects.get(id = product_id)
    return render(request, 'africandesigns/product.html',  {'title': 'Product', 'product': product})


""" shopping cart: each store has a separate shopping cart """
def add_item_to_cart(request, product_id):
    product = Products.objects.get(id = product_id)
    #check if shopping cart is not empty. request.session['shopping-cart'] contains a list of stores whose products are currently added to the shopping cart
    if 'shopping_cart' in request.session:
	print 1
	#check if the store's shopping cart is not empty
        if str(product.store_id) in request.session['shopping_cart']:
	    #current products in store's shopping carts
	    current_products = request.session['shopping_cart'][str(product.store_id)]
	    print "cur1", current_products, request.session['shopping_cart'][str(product.store_id)]
	    #add new product to store's shopping cart
	    current_products.append(product)
	    #print "cu2r", current_products
	    request.session['shopping_cart'][str(product.store_id)] = current_products
	    print 2, request.session['shopping_cart'][str(product.store_id)], current_products, 't'
	    request.session.modified = True

	    #print "curr", current_products
	    #request.session['shopping_cart'][str(product.store_id)].append(product)

	    #print 'b', request.session['shopping_cart'][str(product.store_id)], 't'
	#otherwise, store's shopping cart is empty
	else:
	    #add product to store's shopping cart 
	    request.session['shopping_cart'][str(product.store_id)] = [product]
	    request.session.modified = True
	    print 3
	    
	    
    #otherwise, shopping cart is empty
    else:
	#add store to shopping cart session, and add new product to store
	request.session['shopping_cart'] = {str(product.store_id): [product]}
	print 4

    return HttpResponseRedirect(reverse('africandesigns:shopping_cart')) 

""" shopping cart """
def shopping_cart(request,store_id=None, product_index=None):
    if store_id and product_index:
	print "yes", store_id, product_index

africandesigns/templates/africandesigns/edit_account.html
{% extends "africandesigns/base.html" %}
{% block content %}
<div align = "center">
<a href = "{% url 'africandesigns:shipping' %}" class="btn btn-info btn-small"> Shipping Info </a> 
<a href = "{% url 'africandesigns:edit_account' %}" class="btn btn-info btn-small"> Edit Account Details </a> 
<a href = "{% url 'africandesigns:change_password' %}" class="btn btn-info btn-small"> Change Password </a> <br>
</div>

<h1> Register </h1>
<form action = "/africandesigns/edit_account/" method = "post" >
{% csrf_token %}
<table>
{{ form.as_table }}
<tr>
<td> <input type = "submit" name = "submit" value = "Submit">  </td>
</tr>
</table>
</form>
{% endblock %}

africandesigns/templates/africandesigns/edit_product.html
{% extends "africandesigns/base.html" %}
{% block content %}
<h1> Edit Product </h1>
<form action = "{% url 'africandesigns:edit_product' product_id=product_id %}" method = "post" enctype="multipart/form-data">
{% csrf_token %}
<table>
{{ form.as_table }}
<tr>
<th>Upload up to 3 images:</th>
<td>
<input id="image1" type="file" class="" name="image1" >
</td>
</tr>
<tr>
<th></th>
<td>
<input id="image2" type="file" class="" name="image2">
</td>
</tr>
<tr>
<th></th>
<td>
<input id="image3" type="file" class="" name="image3">
</td>
</tr>
<tr>
<td> <input type = "submit" name = "submit" value = "Submit">  </td>
</tr>
</table>
</form>
{% endblock %}

africandesigns/templates/africandesigns/home.html
{% extends "africandesigns/base.html" %}
{% block content %}



<h1> Welcome!</h1>


{% load staticfiles %}


{% if products|length == 0 %}
   There are no products listed!
{% else %}
<ul class="thumbnails">
    {% for product in products %}
  <li class="span2">
        {% if product.images_set.all|length > 0 %}
	    <div class="thumbnail">
	    {{product.name}} <br>
	    <a href = "{% url 'africandesigns:product' product_id=product.id %}"> <img src = "{% static product.images_set.all.0.image_name %}" alt = "product" width = "260" height = "150"> </a> <br>
	{% else %}
	    <a href = "{% url 'africandesigns:product' product_id=product.id %}"> <img src = "{% static 'dress3.jpg' %}" alt = "product" width = "260" height = "180" > </a> <br>
	{% endif %}
	${{product.price}} <br>
	</div>
  </li>
    {% endfor %}

</ul>

{% endif %}




  <!-- span10 -->
  </div> 

  <div class="span1">
  <!-- span1 -->
  </div> 

<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 



{% endblock %} 

africandesigns/templates/africandesigns/my_orders.html
{% extends 'africandesigns/base.html' %}
{% block content %}
<div align = "center">
<a href = "{% url 'africandesigns:my_orders' %}" class="btn btn-info btn-small"> All Orders </a>
<a href = "{% url 'africandesigns:my_orders' order_filter='pending' %}" class="btn btn-info btn-small"> Pending Orders </a>
<a href = "{% url 'africandesigns:my_orders' order_filter='fulfilled' %}" class="btn btn-info btn-small"> Fulfilled Orders </a>
</div>
{% if orders|length == 0 %}
    You have no orders 
{% else %}
    <table class="table table-hover">
    <tr>
    <th> Date </th>
    <th> Seller </th>
    <th> Shipped </th>
    <th> Product(s) Cost </th>
    <th> Shipping Cost </th>
    <th> Number of Products </th>
    <th>  </th>
    </tr>
    <tr>
    {% for order in orders %}
       <td> {{order.date_ordered}} </td>
       <td> <a href = "{% url 'africandesigns:store' store_id=order.seller.id %}"> {{order.seller.name}} </a> </td>
	{% if order.shipped %}
           <td> Yes </td>
	{% else %}
           <td> No </td>
	{% endif %}
       <td> 1 </td>
       <td> 1 </td>
       <td> {{order.orders_products_set.count}} </td> 
       <th> <a href = "{% url 'africandesigns:my_order' order_id=order.id %}" class="btn btn-small"> View Order <a/> </th>
    {% endfor %}
    </tr>
{% endif %}

  <!-- span10 -->
  </div> 

  <div class="span1">
  <!-- span1 -->
  </div> 

<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 
{% endblock %}

africandesigns/templates/africandesigns/orders.html
{% extends 'africandesigns/base.html' %}
{% block content %}
<div align = "center">
<a href = "{% url 'africandesigns:orders' store_id=store_id %}" class="btn btn-info btn-small"> All Orders </a>
<a href = "{% url 'africandesigns:orders' store_id=store_id order_filter='pending' %}" class="btn btn-info btn-small"> Pending Orders </a>
<a href = "{% url 'africandesigns:orders' store_id=store_id order_filter='fulfilled' %}" class="btn btn-info btn-small"> Fulfilled Orders </a>
</div>
{% if orders|length == 0 %}
    You have no orders 
{% else %}
    <table class="table table-hover">
    <tr>
    <th> Date </th>
    <th> Customer </th>
    <th> Shipped </th>
    <th> Product(s) Cost </th>
    <th> Shipping Cost </th>
    <th> Number of Products </th>
    <th>  </th>
    </tr>
    <tr>
    {% for order in orders %}
       <td> {{order.date_ordered}} </td>
       <td> {{order.buyer.username}} {{order.buyer.first_name}} {{order.buyer.last_name}} </td>
	{% if order.shipped %}
           <td> Yes </td>
	{% else %}
           <td> No </td>
	{% endif %}
       <td> 1 </td>
       <td> 1 </td>
       <td> {{order.orders_products_set.count}} </td> 
       <th> <a href = "{% url 'africandesigns:order' order_id=order.id %}" class="btn btn-info btn-small"> View Order <a/> </th>
    {% endfor %}
    </tr>
{% endif %}

  <!-- span10 -->
  </div> 

  <div class="span1">
  <!-- span1 -->
  </div> 

<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 
{% endblock %}

africandesigns/templates/africandesigns/product.html
{% extends "africandesigns/base.html" %}

{% block content %}

    {% if product.store.owner_id == request.session.user.id %}
	<div align = "center">
	<a href = "{% url 'africandesigns:edit_product' product_id=product.id %}" class="btn btn-info btn-small"> Edit </a> 
	<a href = "{% url 'africandesigns:delete_product' product_id=product.id %}" class="btn btn-info btn-small"> Delete </a> <br>
	</div>
    {% endif %}


<h1> {{ product.name }} </h1>
By <a href = "{% url 'africandesigns:store' store_id=product.store_id %}"> {{product.store.name}} </a> <br><br>
{{product.description}} <br><br>
{% load staticfiles %}

	    <div class="row-fluid">

	    <!-- big image -->
	    <div class="row-fluid">
	    <div class="span8">
	        <img src = "{% static product.images_set.all.0.image_name %}" alt = "product" width = "600" height = "400" class="thumbnail" id = "big-image"> <br>
	    </div>

	    <!-- small image -->
	    <div class="span2">


        {% if product.images_set.all|length > 1 %}


	    {% for image_object in product.images_set.all %}


	        <a onclick = "loadImage('{% static image_object.image_name %}');" href="#"> <img src = "{% static image_object.image_name %}" alt = "product" width = "300" height = "200" class="thumbnail" > </a> 


	    {% endfor %}

	{% endif %}

	    </div>
	    </div>

	    </div>


	${{product.price}} <br>


<a href = "{% url 'africandesigns:add_item_to_cart' product_id=product.id %}" class="btn btn-small"> Add to cart </a> <br>

  <!-- span10 -->
  </div> 

  <div class="span1">
  <!-- span1 -->
  </div> 

<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 







{% endblock %} 

africandesigns/templates/africandesigns/shipping.html
{% extends "africandesigns/base.html" %}
{% block content %}
<div align = "center">
<a href = "{% url 'africandesigns:shipping' %}" class="btn btn-info btn-small"> Shipping Info </a> 
<a href = "{% url 'africandesigns:edit_account' %}" class="btn btn-info btn-small"> Edit Account Details </a> 
<a href = "{% url 'africandesigns:change_password' %}" class="btn btn-info btn-small"> Change Password </a> <br>
</div>

<h1> Shipping Address </h1>
<form action = "{% url 'africandesigns:shipping'%}" method = "post" >
{% csrf_token %}
<table>
{{ form.as_table }}
<tr>
<td> <input type = "submit" name = "submit" value = "Submit" class="btn btn-small">  </td>
</tr>
</table>
</form>

  <!-- span10 -->
  </div> 

  <div class="span1">
  <!-- span1 -->
  </div> 

<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 
{% endblock %}

africandesigns/templates/africandesigns/store.html
{% extends "africandesigns/base.html" %}
{% block content %}

<style type="text/css">
.cover
{
	
	padding:12px;


	width= "100%";
	
background-color:#fcfcfc;
border:1px solid white;
	color:#888;
	margin-bottom:25px;

-moz-border-radius:10px;
	-webkit-border-radius:10px;
	border-radius:10px;

	-moz-box-shadow:2px 2px 0 #c2c2c2;
	-webkit-box-shadow:2px 2px 0 #c2c2c2;
	box-shadow:2px 2px 0 #c2c2c2;
	
}
</style>

<style type="text/css">
div.img
{
  margin: 2px;
  border: 1px solid blue;
  height: auto;
  width: auto;
  float: left;
  text-align: center;
}   
div.img img
{
  display: inline;
  margin: 3px;
  border: 1px solid blue;
}
div.img a:hover img {border: 1px solid yellow;}
div.desc
{
  text-align: center;
  font-weight: normal;
  width: 120px;
  margin: 2px;
}
</style>

{% if store.owner_id == request.session.user.id %}
    <div align = "center">
    <a href = "{% url 'africandesigns:edit_store' store_id=store.id %}" class="btn btn-info btn-small"> Edit </a> 
    <a href = "{% url 'africandesigns:add_product' %}" class="btn btn-info btn-small"> Add Product </a>
    <a href = "{% url 'africandesigns:orders' store_id=store.id %}" class=" btn btn-info btn-small"> Orders </a> 
    <a href = "{% url 'africandesigns:store_admin' store_id=store.id %}" class=" btn btn-info btn-small"> Admins </a> 
    </div>

{% elif is_admin %}
    <div align = "center">
    <a href = "{% url 'africandesigns:edit_store' store_id=store.id %}" class="btn btn-info btn-small"> Edit </a> 
    <a href = "{% url 'africandesigns:add_product' %}" class="btn btn-info btn-small"> Add Product </a>
    <a href = "{% url 'africandesigns:orders' store_id=store.id %}" class=" btn btn-info btn-small"> Orders </a> 
    <a href = "{% url 'africandesigns:store_admin' store_id=store.id %}" class=" btn btn-info btn-small"> Admins </a> 
    </div>

{% endif %}



<h1> Welcome to {{ store.name }}</h1>
{{ store.description }} <br>


{% load staticfiles %}



<script src="{% static 'css/holder.js' %}"></script>

{% if products|length == 0 %} 
   You have no products listed!
{% else %}
<ul class="thumbnails">
    {% for product in products %}
  <li class="span3">
        {% if product.images_set.all|length > 0 %}
	    <div class="thumbnail">
	    {{product.name}} <br>
	    <a href = "{% url 'africandesigns:product' product_id=product.id %}"> <img src = "{% static product.images_set.all.0.image_name %}" alt = "product" width = "200" height = "200"> </a> <br>
	{% else %}
	    <a href = "{% url 'africandesigns:product' product_id=product.id %}"> <img src = "{% static 'dress3.jpg' %}" alt = "product" width = "200" height = "200" > </a> <br>
	{% endif %}
	${{product.price}} <br>
	</div>
  </li>
    {% endfor %}
{% endif %}
</ul>


  <!-- span10 -->
  </div> 

  <div class="span1">
  <!-- span1 -->
  </div> 

<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 



{% endblock %} 